### ISSUE TITLE
intermittent disconnect from /api/refresh-token

### ISSUE THREAD

**Issue by dchan14** [Ntarasiuk/nexthasurajwt#1]
Failed to load resource: the server responded with a status of 401 (Unauthorized)
api/refresh-token:1 

also i left off the       // 'x-hasura-admin-secret': config.hasuraAdminSecret,
b/c it just doesn't seem to connect when i set it so i am not quite sure why i get the above error of refreshing the token
also my .env i made it
JWT_TOKEN_EXPIRES=480
REFRESH_TOKEN_EXPIRES=4800

so i am not sure why this is happening

This is a great starting point and i appreciate your work on this it seems to be the only one that allows for http & websockets work with apollo and hasura AMAZIN!

**Comment by Ntarasiuk** [comment]
Glad you're finding it useful! 🙏🙏
Do you see the tokens being written in your Hasura DB?

**Comment by dchan14** [comment]
Yes it is written
And i hit refresh and somehow it sees token

No matter how i add the hasura admin secret the app cannot seem to use it so i leave it off and it works

**Comment by dchan14** [comment]
well still can't figure it out but i was able to use this boilerplate for jwt and your withApollo/ApolloClient to get what i needed.

Again thanks for the simplicity in the subscriptions and client code.  I still don't know why the admin-secret does not work in the headers but this works for what i need.
